# Site settings
title: Mythreyi Ramesh
email: mythreyi.rr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Homepage of Mythreyi Ramesh, 4th Year Dual Degree (B.Tech in Metallurgical and Materials Engineering + M.Tech in Computational Engineering), Indian Institute of Technology Madras, India.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  mythreyiramesh

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Undergraduate Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""