# Site settings
title: Mythreyi Ramesh
email: mythreyiramesh7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website of Mythreyi Ramesh, a final year undergraduate student at the Indian Institute of Technology Madras, Chennai, India.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  mythreyiramesh

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
